language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-mm-campaign' ]; then cd .. && eval "mv $currentfolder generator-mm-campaign" && cd generator-mm-campaign; fi

